import React, { useState, useEffect } from "react";
import personService from "./services/persons";

const Notification = ({ message }) => {
  return (
    <div className="notification">
      <p>{message}</p>
    </div>
  );
};

const Person = ({ person, handleDelete }) => {
  return (
    <div>
      {person.name} {person.number}{" "}
      <button
        onClick={() => {
          handleDelete(person.id, person.name);
        }}
      >
        delete
      </button>
    </div>
  );
};

const Filter = ({ handleFilter }) => {
  return (
    <div>
      <label htmlFor="filterInput">The filter shown with </label>
      <input type="text" id="filterInput" onChange={handleFilter} />
    </div>
  );
};

const PersonForm = ({
  newName,
  newNumber,
  handleSubmit,
  handleNewName,
  handleNewNumber,
}) => {
  return (
    <form onSubmit={handleSubmit}>
      <div>
        name: <input type="text" value={newName} onChange={handleNewName} />
      </div>
      <div>
        number:{" "}
        <input type="text" value={newNumber} onChange={handleNewNumber} />
      </div>
      <div>
        <button type="submit">Add</button>
      </div>
    </form>
  );
};

const Persons = ({ personsToShow, handleDelete }) => {
  return (
    <div>
      {personsToShow.map((person, index) => {
        return (
          <Person key={index} person={person} handleDelete={handleDelete} />
        );
      })}
    </div>
  );
};

function App() {
  const [persons, setPersons] = useState([]);
  const [newName, setNewName] = useState("");
  const [newNumber, setNewNumber] = useState("");
  const [filterInput, setFilterInput] = useState("");
  const [notificationMessage, setNotificationMessage] = useState("");

  useEffect(() => {
    personService.getAll().then((persons) => {
      setPersons(persons);
    });
  }, []);

  const handleSubmit = (event) => {
    event.preventDefault();
    const personObject = {
      // id not included as will be auto generated by the backend.
      name: newName,
      number: newNumber,
    };
    const filteredPersons = persons.filter((person) => {
      return person.name === newName;
    });
    if (filteredPersons.length > 0) {
      if (
        window.confirm(
          `${filteredPersons[0].name} is already added to phonebook, replace the old number with a new one?`
        )
      ) {
        personService
          .updatePerson(filteredPersons[0].id, personObject)
          .then((updatedPerson) => {
            setPersons(
              persons.map((person) => {
                return person.id !== filteredPersons[0].id
                  ? person
                  : updatedPerson; // we use the data returned from put request as the object contains the id for the updated person
              })
            );
            showNotification(`You have updated ${updatedPerson.name}`);
          });
      }
    } else {
      personService.createPerson(personObject).then((newPerson) => {
        setPersons(persons.concat(newPerson));
        showNotification(`Added ${newPerson.name}`);
      });
    }
    setNewName("");
    setNewNumber("");
  };
  const handleNewName = (event) => {
    setNewName(event.target.value);
  };
  const handleNewNumber = (event) => {
    setNewNumber(event.target.value);
  };
  const handleDelete = (id, name) => {
    if (window.confirm(`Delete ${name}`)) {
      personService.deletePerson(id).then((response) => {
        setPersons(persons.filter((person) => person.id !== id));
      });
    }
  };
  const handleFilter = (event) => {
    setFilterInput(event.target.value);
  };

  const showNotification = (message) => {
    setNotificationMessage(message);
    setTimeout(() => {
      setNotificationMessage("");
    }, 5000);
  };

  const personsToShow = filterInput
    ? persons.filter((person) => {
        return person.name.toLowerCase().includes(filterInput.toLowerCase());
      })
    : persons;
  return (
    <div>
      <h2>Phonebook</h2>
      {notificationMessage ? (
        <Notification message={notificationMessage} />
      ) : null}
      <Filter handleFilter={handleFilter} />
      <h2>Add A New</h2>
      <PersonForm
        newName={newName}
        newNumber={newNumber}
        handleSubmit={handleSubmit}
        handleNewName={handleNewName}
        handleNewNumber={handleNewNumber}
      />
      <h2>Numbers</h2>
      <Persons personsToShow={personsToShow} handleDelete={handleDelete} />
    </div>
  );
}

export default App;
